# Data Overview

In [2]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")

print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [3]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
df.shape

(891, 15)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [6]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
df.embark_town.unique()

<StringArray>
['Southampton', 'Cherbourg', 'Queenstown', nan]
Length: 4, dtype: str

In [8]:
# df.drop(['embarked', 'class', 'who', 'adult_male', 'deck', 'alive', 'alone'], axis=1, inplace=True)

In [9]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [10]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [12]:
# df.duplicated().sum()

In [13]:
# df = df.drop_duplicates().reset_index(drop=True)
# print(df)

In [14]:
df.age.min()

np.float64(0.42)

In [15]:
df.age.max()

np.float64(80.0)

In [16]:
df['age'] = df['age'].fillna(df['age'].median())
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female  28.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [17]:
df.deck.unique()

[NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, str): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [18]:
df['deck'] = df['deck'].fillna(df['deck'].mode()[0])
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])


print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female  28.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True    C  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False    C  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True    C  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True    C  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False    C  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True    C   Queenstown    no   True

[891 rows x 15 columns]

In [19]:
# df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
# The important thing is that mode() can actually have more than one answer
#  if two or more values are equally common.
#mode()[0]It is only used to get the actual first value from the result of mode().
# print(df)

In [20]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         891 non-null    category
 12  embark_town  891 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [22]:
df['age'] = df['age'].round().astype(float)
print(df)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female  28.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True    C  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False    C  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True    C  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True    C  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False    C  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True    C   Queenstown    no   True

[891 rows x 15 columns]

In [23]:
df['sex'] = df['sex'].str.lower().replace({
    'male' : 'M',
    'female' : 'F',
    'm' :'M',
    'f' : 'F'})
print(df)

     survived  pclass sex   age  sibsp  parch     fare embarked   class  \
0           0       3   M  22.0      1      0   7.2500        S   Third
1           1       1   F  38.0      1      0  71.2833        C   First
2           1       3   F  26.0      0      0   7.9250        S   Third
3           1       1   F  35.0      1      0  53.1000        S   First
4           0       3   M  35.0      0      0   8.0500        S   Third
..        ...     ...  ..   ...    ...    ...      ...      ...     ...
886         0       2   M  27.0      0      0  13.0000        S  Second
887         1       1   F  19.0      0      0  30.0000        S   First
888         0       3   F  28.0      1      2  23.4500        S   Third
889         1       1   M  26.0      0      0  30.0000        C   First
890         0       3   M  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True    C  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False    C  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True    C  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True    C  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False    C  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True    C   Queenstown    no   True

[891 rows x 15 columns]

In [24]:
df['embark_town']= df['embark_town'].str.title()
print(df)

     survived  pclass sex   age  sibsp  parch     fare embarked   class  \
0           0       3   M  22.0      1      0   7.2500        S   Third
1           1       1   F  38.0      1      0  71.2833        C   First
2           1       3   F  26.0      0      0   7.9250        S   Third
3           1       1   F  35.0      1      0  53.1000        S   First
4           0       3   M  35.0      0      0   8.0500        S   Third
..        ...     ...  ..   ...    ...    ...      ...      ...     ...
886         0       2   M  27.0      0      0  13.0000        S  Second
887         1       1   F  19.0      0      0  30.0000        S   First
888         0       3   F  28.0      1      2  23.4500        S   Third
889         1       1   M  26.0      0      0  30.0000        C   First
890         0       3   M  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True    C  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False    C  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True    C  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True    C  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False    C  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True    C   Queenstown    no   True

[891 rows x 15 columns]

In [25]:
df.embarked.unique()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [26]:
df.duplicated().sum()

np.int64(115)

In [27]:
df = df.drop_duplicates().reset_index(drop=True)
print(df)

     survived  pclass sex   age  sibsp  parch     fare embarked  class    who  \
0           0       3   M  22.0      1      0   7.2500        S  Third    man
1           1       1   F  38.0      1      0  71.2833        C  First  woman
2           1       3   F  26.0      0      0   7.9250        S  Third  woman
3           1       1   F  35.0      1      0  53.1000        S  First  woman
4           0       3   M  35.0      0      0   8.0500        S  Third    man
..        ...     ...  ..   ...    ...    ...      ...      ...    ...    ...
771         0       3   F  39.0      0      5  29.1250        Q  Third  woman
772         1       1   F  19.0      0      0  30.0000        S  First  woman
773         0       3   F  28.0      1      2  23.4500        S  Third  woman
774         1       1   M  26.0      0      0  30.0000        C  First    man
775         0       3   M  32.0      0      0   7.7500        Q  Third    man

     adult_male deck  embark_town alive  alone
0          True    C  Southampton    no  False
1         False    C    Cherbourg   yes  False
2         False    C  Southampton   yes   True
3         False    C  Southampton   yes  False
4          True    C  Southampton    no   True
..          ...  ...          ...   ...    ...
771       False    C   Queenstown    no  False
772       False    B  Southampton   yes   True
773       False    C  Southampton    no  False
774        True    C    Cherbourg   yes   True
775        True    C   Queenstown    no   True

[776 rows x 15 columns]

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df.survived.value_counts()

survived
0    454
1    322
Name: count, dtype: int64

In [30]:
df.groupby(["sex","survived"])["survived"].count()

sex  survived
F    0            76
     1           217
M    0           378
     1           105
Name: survived, dtype: int64

In [31]:
df.groupby(["alone","survived"])["survived"].count()

alone  survived
False  0           165
       1           173
True   0           289
       1           149
Name: survived, dtype: int64

In [34]:
df.to_csv("Cleaned_Titanic_dataset.csv", index=True)